const cars=[
 {brand:'BMW',model:'5 Series 530i',year:2023,mileage:23500,engine:'2.0 л',transmission:'Автомат',drive:'2WD',price:6490000,tag:'В наличии',img:'https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=900&q=85'},
 {brand:'Mercedes-Benz',model:'E-Class E 200',year:2022,mileage:31200,engine:'2.0 л',transmission:'Автомат',drive:'2WD',price:6190000,tag:'В наличии',img:'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=900&q=85'},
 {brand:'Porsche',model:'Cayenne',year:2023,mileage:12600,engine:'3.0 л',transmission:'Автомат',drive:'4WD',price:11390000,tag:'Проверен',img:'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=900&q=85'},
 {brand:'Toyota',model:'Land Cruiser 300',year:2024,mileage:5800,engine:'3.5 л',transmission:'Автомат',drive:'4WD',price:14500000,tag:'В наличии',img:'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=900&q=85'},
 {brand:'Audi',model:'A6 45 TFSI',year:2023,mileage:19700,engine:'2.0 л',transmission:'Автомат',drive:'4WD',price:7390000,tag:'В наличии',img:'https://images.unsplash.com/photo-1606152421802-db97b9c7a11b?auto=format&fit=crop&w=900&q=85'},
 {brand:'BMW',model:'X5 xDrive40i',year:2024,mileage:18500,engine:'3.0 л',transmission:'Автомат',drive:'4WD',price:9490000,tag:'Автомобиль дня',img:'https://images.unsplash.com/photo-1556189250-72ba954cfc2b?auto=format&fit=crop&w=900&q=85'},
 {brand:'Mercedes-Benz',model:'GLE 450',year:2023,mileage:26800,engine:'3.0 л',transmission:'Автомат',drive:'4WD',price:10250000,tag:'Проверен',img:'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=900&q=85'},
 {brand:'Toyota',model:'Camry 2.5',year:2022,mileage:38900,engine:'2.5 л',transmission:'Автомат',drive:'2WD',price:3990000,tag:'В наличии',img:'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=900&q=85'}
];
const rub=n=>new Intl.NumberFormat('ru-RU').format(n)+' ₽';
function card(c){return `<article class="car-card"><div class="car-img"><img src="${c.img}" alt="${c.brand} ${c.model}"><span class="car-tag">${c.tag}</span></div><div class="car-body"><h3 class="car-title">${c.brand} ${c.model}</h3><div class="car-meta"><span>${c.year} год</span><span>${new Intl.NumberFormat('ru-RU').format(c.mileage)} км</span><span>${c.engine}</span><span>${c.transmission}</span><span>${c.drive}</span></div><p class="car-price">${rub(c.price)}</p><a class="card-link modal-open" href="#">Подробнее <span>↗</span></a></div></article>`}
document.querySelector('#popular-grid').innerHTML=cars.slice(0,4).map(card).join('');
function renderCatalog(list=cars){document.querySelector('#catalog-grid').innerHTML=list.slice(0,6).map(card).join('');document.querySelector('#cars-count').textContent=`${list.length} автомобилей`;observe();}
renderCatalog();
const modal=document.querySelector('#modal');document.addEventListener('click',e=>{if(e.target.closest('.modal-open')){e.preventDefault();modal.classList.add('active')}if(e.target===modal||e.target.closest('.modal-close'))modal.classList.remove('active')});
document.querySelectorAll('form').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();modal.classList.remove('active');document.querySelector('#toast').classList.add('show');setTimeout(()=>document.querySelector('#toast').classList.remove('show'),3500)}));
document.querySelector('#sort-cars').addEventListener('change',e=>{let copy=[...cars];if(e.target.value==='price')copy.sort((a,b)=>a.price-b.price);if(e.target.value==='year')copy.sort((a,b)=>b.year-a.year);if(e.target.value==='mileage')copy.sort((a,b)=>a.mileage-b.mileage);renderCatalog(copy)});
document.querySelector('#apply-filters').addEventListener('click',()=>{let b=document.querySelector('#brand-filter').value;renderCatalog(b?cars.filter(c=>c.brand===b):cars)});document.querySelector('#reset-filters').addEventListener('click',()=>{document.querySelector('#brand-filter').value='';renderCatalog()});
document.querySelector('.menu-toggle').addEventListener('click',()=>{document.querySelector('nav').classList.toggle('mobile-nav')});
window.addEventListener('scroll',()=>document.querySelector('.header').classList.toggle('scrolled',scrollY>20));
function observe(){const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.1});document.querySelectorAll('.reveal:not(.visible),.car-card:not(.visible)').forEach(el=>io.observe(el))}observe();
